apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-deploy
spec:
  replicas: {{ .Values.ReplicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 80
